### ISSUE TITLE
Server Instance on 1.18.1 Fabric crash

### ISSUE THREAD

**Issue by itsdinkd** [Darkhax-Minecraft/AttributeFix#19]
```java
[19:31:26] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.RuntimeException: Mixin transformation of net.darkhax.attributefix.mixin.AccessorRangedAttribute failed
        at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.6) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at net.darkhax.attributefix.config.AttributeConfig.applyChanges(AttributeConfig.java:47) ~[AttributeFix-Fabric-1.18.1-13.0.1.jar:?]
        at net.darkhax.attributefix.AttributeFixFabricServer.lambda$onInitializeServer$0(AttributeFixFabricServer.java:20) ~[AttributeFix-Fabric-1.18.1-13.0.1.jar:?]
        at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:48) ~[fabric-lifecycle-events-v1-1.4.1+c15ca335c8-83bdf7047940da8a.jar:?]
        at net.minecraft.server.MinecraftServer.handler$dfh000$afterSetupServer(MinecraftServer:9273) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:663) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: org.spongepowered.asm.mixin.transformer.throwables.IllegalClassLoadError: Illegal classload request for net.darkhax.attributefix.mixin.AccessorRangedAttribute. Mixin is defined in attributefix.mixins.json and cannot be referenced directly
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:334) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.12.12.jar:?]
        ... 10 more
[19:31:26] [Server thread/ERROR]: This crash report has been saved to: C:\Users\\Downloads\aqm2-server\test3\.\crash-reports\crash-2021-12-18_19.31.26-server.txt
```

**Comment by Darkhax** [comment]
Thanks for the report, this should be fixed in the new version. https://www.curseforge.com/minecraft/mc-mods/attributefix/files/3571697

Fixes for 1.17 and 1.18 will be released soon.
