### ISSUE TITLE
  AttributeFix-Forge-1.18.1-13.0.2.jar makes server crash 

### ISSUE THREAD

**Issue by linxmedaille** [Darkhax-Minecraft/AttributeFix#20]
Forge: net.minecraftforge:39.0.5[16:08:16] [main/FATAL]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        AttributeFix (attributefix) encountered an error during the complete event phase
º7org.spongepowered.asm.mixin.transformer.throwables.IllegalClassLoadError: Illegal classload request for net.darkhax.attributefix.mixin.AccessorRangedAttribute. Mixin is defined in attributefix.mixins.json and cannot be referenced directly
]
        at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:235) ~[fmlcore-1.18.1-39.0.5.jar%2363!:?]
        at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$21(ModLoader.java:200) ~[fmlcore-1.18.1-39.0.5.jar%2363!:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:200) ~[fmlcore-1.18.1-39.0.5.jar%2363!:?]
        at net.minecraftforge.fml.ModLoader.lambda$finishMods$17(ModLoader.java:189) ~[fmlcore-1.18.1-39.0.5.jar%2363!:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at net.minecraftforge.fml.ModLoader.finishMods(ModLoader.java:189) ~[fmlcore-1.18.1-39.0.5.jar%2363!:?]
        at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:48) ~[forge-1.18.1-39.0.5-universal.jar%2366!:?]
        at net.minecraft.server.Main.main(Main.java:104) ~[server-1.18.1-20211210.034407-srg.jar%2362!:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:46) ~[fmlloader-1.18.1-39.0.5.jar%2323!:?]
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?]
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?]
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?]
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?]
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?]
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?]

C:\Users\pyoup\Desktop\server custom modéed>pause
Appuyez sur une touche pour continuer...

**Comment by Darkhax** [comment]
Not sure why you closed this issue right away, but I fixed the issue and 13.0.3 is now live on Curseforge.
